tm.feedback =  "deep_sky_blue1"
tm.error =  "red3"
tm.status =  "deep_sky_blue1"
tm.help.section =  "gold1"
tm.help.command =  "magenta3"
tm.usage.prog =  "magenta3"
tm.usage.groups =  "gold1"
tm.usage.args =  "cyan"
tm.usage.metavar =  "dark_cyan"
tm.usage.help =  "default"
tm.usage.text =  "default"
tm.usage.syntax =  "bold"
tm.list.header =  "bold deep_sky_blue1"
tm.list.border =  "bold deep_sky_blue1"
tm.app.running =  "green1"
tm.app.stopped =  "red3"
tm.app.sessions =  "cyan1"
tm.setting.name =  "dark_orange3"
tm.setting.equals =  "orchid1"
tm.setting.comment =  "pale_turquoise4"
tm.setting.string =  "green1"
tm.setting.bool =  "purple"
tm.setting.int =  "royal_blue1"
tm.setting.float =  "royal_blue1"
