# dark theme for tomcat-manager
# intended for use on dark colored terminal backgrounds
# works on 256 color terminals
# see https://rich.readthedocs.io/en/stable/appendix/colors.html#appendix-colors
# for supported list of color names

[tm]
feedback =  "deep_sky_blue1"
error =  "red3"
status =  "deep_sky_blue1"

[tm.help]
section =  "gold1"
command =  "magenta3"

[tm.usage]
prog =  "magenta3"
groups =  "gold1"
args =  "cyan"
metavar =  "dark_cyan"
help =  "default"
text =  "default"
syntax =  "bold"

[tm.list]
header =  "bold deep_sky_blue1"
border =  "bold deep_sky_blue1"

[tm.app]
running =  "green1"
stopped =  "red3"
sessions =  "cyan1"

[tm.setting]
name =  "dark_orange3"
equals =  "orchid1"
comment =  "pale_turquoise4"
string =  "green1"
bool =  "purple"
int =  "royal_blue1"
float =  "royal_blue1"

[tm.theme]
section = "gold1"
