# theme template for tomcat-manager
#
# This file is in TOML format, see https://toml.io/en/ for more information.
#
# A theme consists of elements and a style for each element.
#
# In this example:
#
#   [tm.help]
#   section = "gold1"
#
# "tm.help.section" is the theme element, and "gold1" is the style. The TOML file
# format allows you to specify the theme element using several different
# syntaxes. This syntax yields the same result:
#
#   tm.help.section = "gold1"
#
# All theme elements are present in this file, but set to "default".
# The theme elements are all present to make it easy for you to
# customize them. "default" means to apply no color or styling, making this
# theme template the visual equivilent of no theme.
#
# You can set a style for each theme element. A style can specify colors
# and attributes (like bold or italic). Really old terminals could display
# 16 colors, old terminals can display 256 colors, most modern terminals
# can display 16.7 million colors.
#
# Specify a color using any of the following:
#
#   #8700af           CSS-style hex notation
#   rgb(135,0,175)    RGB form using three integers
#   dark_magenta      color names
#   color(91)         color numbers
#
# Color names and numbers are shown at
# https://rich.readthedocs.io/en/stable/appendix/colors.html
#
# All of the above forms produce the exact same color.
#
# By itself, a color will set the foreground color. To set the background
# color, preceed the color with the word "on".
#
#   white on rgb(135,0,75)
#   #ffffff on dark_magenta
#
# Specify additional text attributes by adding additional words to the style:
#
#   #ffffff on #8700af bold strike
#   color(91) underline
#
# The most useful text attributes are:
#
#   bold        bold text
#   italic      italic text (not supported on Windows)
#   strike      text with a strikethrough line
#   underline   underlined text
#
# For more examples and additional documentation on styles, see
# https://rich.readthedocs.io/en/stable/style.html
#
# More documentation on themes and how they work is available at
# https://tomcatmanager.readthedocs.io/en/stable/interactive/themes.html
#


[tm]
error =  "default"
status =  "default"
animation = "default"

[tm.help]
section =  "default"
command =  "default"

[tm.usage]
prog =  "default"
groups =  "default"
args =  "default"
metavar =  "default"
help =  "default"
text =  "default"
syntax =  "default"

[tm.list]
header =  "default"
border =  "default"

[tm.app]
running =  "default"
stopped =  "default"
sessions =  "default"

[tm.setting]
name =  "default"
equals =  "default"
comment =  "default"
string =  "default"
bool =  "default"
int =  "default"
float =  "default"

[tm.theme]
section = "default"
